/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaohuijun_administrator_mymvp_NativeUtils */

#ifndef _Included_com_xiaohuijun_administrator_mymvp_NativeUtils
#define _Included_com_xiaohuijun_administrator_mymvp_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaohuijun_administrator_mymvp_NativeUtils
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xiaohuijun_administrator_mymvp_NativeUtils_getStringFromNative
  (JNIEnv *env, jclass jobj){
  return (*env)->NewStringUTF(env,"Hello From JNI!");}


#ifdef __cplusplus
}
#endif
#endif
